export const endpoints = {
  signIn: "bmgt435/api/auth/sign-in",
  signUp: "bmgt435/api/auth/sign-up",
  forgetPassword: "bmgt435/api/auth/forget-password",
  me: "bmgt435/api/users/me",
  users: "bmgt435/api/users",
  usersPaginated: "bmgt435/api/users-paginated",
  tags: "bmgt435/api/tags",
  tagsPaginated: "bmgt435/api/tags-paginated",
  groups: "bmgt435/api/groups",
  groupsPaginated: "bmgt435/api/groups-paginated",
  roles: "bmgt435/api/roles",
  rolesPaginated: "bmgt435/api/roles-paginated",
  cases: "bmgt435/api/cases",
  casesPaginated: "bmgt435/api/cases-paginated",
  caseRecords: "bmgt435/api/case-records",
  caseRecordsPaginated: "bmgt435/api/case-records-paginated",
};